### ISSUE TITLE
Bus routes with two stops

### ISSUE THREAD

**Issue by SimSon2710** [MARS-Group-HAW/model-soh#3]
Hey,

the current [validation in `BusDriver`](https://github.com/MARS-Group-HAW/model-soh/blob/47a62b93fea07b1aeea66850c3c050d60718a520/SOHModel/Bus/Model/BusDriver.cs#L142C1-L143C82) checks if the bus route contains fewer than two route sections, which could cause an exception to be thrown for valid routes that have two stops but only one route section. Regarding the exception text, it's possible that the intention of the check was to ensure that there are at least two stops on a route. 

I would suggest to instead check on `BusRoute.Count() < 1` as this implies to have at least two stops.

Cheers!

**Comment by furoriano** [comment]
Hello,
it's a long time, but I vaguely recall that there was a problem with routes that only have one section. But I can also be mistaken. So, yes I would also suggest to try to change the _check_ and build a simple scenario with only one bus driving this route of one section to see if it works as intended.
Can you give feedback here, if the problem could be solved? Thanks!

**Comment by SimSon2710** [comment]
Hey @furoriano,

It took me some time, but I now opened a PR which should solve the issue. As you proposed, I also added a test, to verify the new functionality.

All the Best!
